DROP TABLE IF EXISTS TB_PRODUTO;

CREATE TABLE TB_PRODUTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(250) NOT NULL,
    VALOR_UNITARIO VARCHAR(250) NOT NULL,
    DESCRICAO VARCHAR(250) NOT NULL
);